export enum ErrorType {
  InvalidToken = 'INVALID_TOKEN',
  AccessTokenExpired = 'ACCESS_TOKEN_EXPIRED',
  RefreshTokenExpired = 'REFRESH_TOKEN_EXPIRED',
  PermissionExists = 'PERMISSION_EXISTS',
  RoleExists = 'ROLE_EXISTS',
  UserExists = 'USER_EXISTS',
  InvalidCurrentPassword = 'INVALID_CURRENT_PASSWORD',
  InvalidCredentials = 'INVALID_CREDENTIALS',
  BlockedUser = 'BLOCKED_USER',
  InactiveUser = 'INACTIVE_USER',
  ForeignKeyConflict = 'FOREIGN_KEY_CONFLICT',
  AlreadyExists = 'ALREADY_EXISTS',
  PropertyAlreadyAllocated = 'PROPERTY_ALREADY_ALLOCATED',
  TermSettingsExist = 'TERM_SETTINGS_EXIST',
  InvalidCurrentPin = 'INVALID_CURRENT_PIN',
  PaymentVerificationFailed = 'PAYMENT_VERIFICATION_FAILED',
}
