export enum PaymentMethod {
  CREDIT = 'credit',
  DEBIT = 'debit',
  TRANSFER = 'transfer',
  WALLET = 'wallet',
  CARD = 'card',
  BANK = 'bank',
  VIRTUAL_ACCOUNT = 'virtual_account',
  QR_CODE = 'qr_code',
  USSD = 'ussd',
  CASH = 'cash',
  CHEQUE = 'cheque',
  DIRECT_DEBIT = 'direct_debit',
  STANDING_ORDER = 'standing_order',
  MOBILE_MONEY = 'mobile_money',
  REMITA = 'remita',
  APPLE_PAY = 'apple_pay',
  GOOGLE_PAY = 'google_pay',
  OTHER = 'other',
  UNKNOWN = 'unknown',
}
